# Generated by Django 3.1.6 on 2021-02-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pok_name', models.CharField(max_length=200)),
                ('pok_height', models.IntegerField()),
                ('pok_weight', models.IntegerField()),
                ('pok_img_url', models.URLField()),
                ('pok_abilitys', models.ManyToManyField(to='pok_api.Ability')),
            ],
        ),
    ]
